spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysqlrootpassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        type:
          preferred_uuid_jdbc_type: CHAR
  sql:
    init:
      mode: never  # SQL 스크립트 실행 안 함

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn

server:
  port: 2020