spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysqlrootpassword
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 2020